import "./globals.css";



export const metadata = {
  title: "Zillow Clone",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
